// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Pour les migrations, on utilise DIRECT_URL si disponible (connexion directe sans pooler)
    // En local, DIRECT_URL = DATABASE_URL. Sur Neon : DIRECT_URL = connexion non-poolée
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
